# Generated by Django 3.1.5 on 2021-01-13 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210113_1034'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Associates',
        ),
    ]
